### ISSUE TITLE
cython_bbox.pyx file not being found at the expected location.

### ISSUE THREAD

**Issue by Prashan081003** [jdyjjj/All-in-One-Gait#18]
I'm encountering an issue when trying to run step 3

Traceback (most recent call last):
  File "/content/All-in-one-Gait/openait/demo/libs/main.py", line 8, in <module>
    from tracker.byte_tracker import ByteTracker
  File "/content/All-in-one-Gait/openait/demo/libs/tracker/byte_tracker.py", line 19, in <module>
    from common.lib import helpers
ImportError: cannot import name 'helpers' from 'common.lib'

**Comment by ronka11** [comment]
Did you find a solution? Even I cannot find src/cython_bbox.pyx

When I run the python program I get the following error. Tried all solutions mentioned (like upgrading numpy but that gives library versions discrepancies with other libraries, did not find any 'np.float' in the other python files).

>  Traceback (most recent call last):
>   File "/content/All-in-One-Gait/OpenGait/demo/libs/main.py", line 6, in <module>
>     from track import *
>   File "/content/All-in-One-Gait/OpenGait/demo/libs/track.py", line 15, in <module>
>     from tracker.byte_tracker import BYTETracker
>   File "/content/All-in-One-Gait/OpenGait/demo/libs/tracker/byte_tracker.py", line 10, in <module>
>     from tracker import matching
>   File "/content/All-in-One-Gait/OpenGait/demo/libs/tracker/matching.py", line 7, in <module>
>     from cython_bbox import bbox_overlaps as bbox_ious
>   File "src/cython_bbox.pyx", line 12, in init cython_bbox
>   File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 324, in __getattr__
>     raise AttributeError(__former_attrs__[attr])
> AttributeError: module 'numpy' has no attribute 'float'.
> `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
>     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
